### PR TITLE
Fix Nav compilation issues and add textmode option to NAV process

### PR DESCRIPTION
**Pull request by powerlord**
Make the Nav Process use a logfile to determine when the nav file is completely written.

Also add a textmode option to the NAV process.

### CODE REVIEW

**Comment by powerlord** [comment]
On a side note, I've only tested this with Team Fortress 2, although I'm assuming other games use the same message when they complete NAV generation.

**Comment by maxdup** [comment]
This is interesting, I like your approach. You'd be surprised how different the engine branches can be in regards to nav building tho, so there's definitely some tests to be done here. This looks like it would be pretty robust tho, I'll give you that.

Also when you say "Fix Nav compilation issues", would you mind detailing the issues you've encountered?

**Comment by powerlord** [comment]
@maxdup Apparently if a map is complicated enough, the FileSystemWatcher may see the nav file and terminate the game process before the nav file is completely written to disk.

Or so it looked when UEAKCrash was working on the TF2 map cp_stoneyridge_event, which ended up having strange crashing issues if CompilePal created it, but it worked fine if he manually generated it.

**Comment by maxdup** [comment]
cool, I was wondering if that would eventually happen. so that's cleared up.

**Comment by ruarai** [comment]
I'll push this. We'll have to see if any issues crop up!

**Pull request merged**
