### PR TITLE
Better support for CS:GO 

### PR DESCRIPTION
**Pull request by gortnarj**
Added new CS:GO texture keys, upper and lower radars and some new vbsp and vrad parameters.

### CODE REVIEW

**Comment by ruarai** [comment]
Seems good by me.

@maxdup ?

**Comment by maxdup** [comment]
I fully approve

**Comment by ruarai** [comment]
Sweet! I think it's also about time we think about a new release version. Thoughts?

**Comment by maxdup** [comment]
yes, there's a lot of things I'd like to fix but I haven't quite found the time to do

**Pull request merged**
