### PR TITLE
Fix packing for paths outside of game folder

### PR DESCRIPTION
**Pull request by gortnarj**
Fix for external paths in gameinfo.txt (eg C:/Dropbox/content). Before it would ignore the path.
Also includes fix for paths with spaces (eg C:/Google Drive/content) where it would mount just the first part (C:/Google).

### CODE REVIEW

**Comment by CaskoChan** [comment]
This would be perfect

**Comment by Exactol** [comment]
Sorry for the long wait.
Looks like external paths were already added in this commit 2427c8bf7d92c9ca92363758f44551e0ccac6850
Does this change offer any improvements?

**Comment by gortnarj** [comment]
Yeah my bad, didn't see that commit. 
Though you can update vmfmaterialkeys.txt and texturekeys.txt, I added some new parameters.

**Comment by Exactol** [comment]
Merged texture/material key commits

**Pull request closed without merging**
